name: Docker CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar          

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar          

      - uses: actions/upload-artifact@master
        with:
          name: jar-file
          path: app.jar
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.SUPER_USUARIO }}
          DOCKER_PASSWORD: ${{ secrets.CLAVE }}
        run : docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.io
      - name: Build Docker image with latest tag
        run: docker build . --file Dockerfile --tag juangomezru/puntosunisabana:latest
      - name: Publish dockerimage to docker hub
        run: docker push juangomezru/puntosunisabana:latest