name: Continous Integrations
on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        name: Instalando javita
        with:
            distribution: 'corretto'
            java-version: '17'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
             arguments: build

      - name: Correr pruebas
        run: ./gradlew test

      - name: Correr prueba Coverage
        run: ./gradlew jacocoTestReport

      - name: Generar JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv